[package]
name = "turmoil"
# When releasing to crates.io:
# - Update version number
#   - README.md
# - Update CHANGELOG.md
# - Create git tag
version = "0.2.0"
edition = "2021"
license = "MIT"
authors = ["Carl Lerche <me@carllerche.com>"]
description = "Simulation testing framework for distributed systems"
homepage = "https://github.com/tokio-rs/turmoil"
repository = "https://github.com/tokio-rs/turmoil"
readme = "README.md"
keywords = ["Deterministic", "Simulation", "Testing"]
categories = ["asynchronous", "network-programming", "simulation"]

[dependencies]
indexmap = "1.9"
rand = { version = "0.8.5", features = ["small_rng"] }
rand_distr = "0.4.3"
scoped-tls = "1.0.0"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"
tokio = { version = "1.19.2", features = ["rt", "sync"] }
tokio-test = { version = "0.4.2" }
